name: dev to master

on:
  workflow_dispatch:
  schedule:
    # At 00:00 on every day-of-week from Monday through Friday.
    - cron: '0 0 * * 1-5'

jobs:
  continuous-pull-request-job:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv --upgrade-strategy=only-if-needed
        pipenv install --dev

    - name: Run
      run: |
        pipenv run python main.py --head dev --base master
      env:
        OWNER: ${{ secrets.OWNER }}
        REPO: ${{ secrets.REPO }}
        TOKEN_REPO_SCOPE: ${{ secrets.TOKEN_REPO_SCOPE }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_MESSAGE_CHANNEL: ${{ secrets.SLACK_MESSAGE_CHANNEL }}
        PR_BODY: ${{ secrets.PR_BODY }}

    - name: Slack Notification on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: mailbox_yuu-eguci
        SLACK_COLOR: good
        SLACK_ICON: https://ca.slack-edge.com/TBHT9GQ5Q-UBHUQ6DEW-03036dfcdb7f-512
        SLACK_MESSAGE: ${{ job.status }}
        SLACK_TITLE: Continuous Pull Request job succeeded
        SLACK_USERNAME: ContinuousPullRequest
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Slack Notification on Failure
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_CHANNEL: mailbox_yuu-eguci
        SLACK_COLOR: danger
        SLACK_ICON: https://ca.slack-edge.com/TBHT9GQ5Q-UBHUQ6DEW-03036dfcdb7f-512
        SLACK_MESSAGE: ${{ job.status }}
        SLACK_TITLE: Continuous Pull Request job failed
        SLACK_USERNAME: ContinuousPullRequest
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
